### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by zyarpa** [zhbink/2017-IndustryBigData#2]
博主，你好，我最近也在研究机器学习，能把数据集发我吗？
邮箱dhuxx_zy@163.com
谢谢！

**Comment by a1147432317** [comment]
能不能发我下，1147432317@qq.com

**Comment by tangletit** [comment]
请求发我下，646277312@qq.com

**Comment by RainbowPillow** [comment]
求数据集， chengxutjut@gmail.com

**Comment by yangyang117** [comment]
求数据集，17732239091@163.com
